apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app1
    ungdung: ungdung1
  name: ungdungnode
spec:
  containers:
  - name: c1
    image: ngovanhuy0241/k8s_container:node
    # imagePullPolicy: Always
    resources:
      limits:
        memory: "150M"
        cpu: "100m"
    env:
    - name: PORT
      value: "8085"
    ports:
      - containerPort: 8085
      # - containerPort: 8086