apiVersion: v1
kind: Pod
metadata:
  name: rsapp
  labels:
    app: rsapp
spec:
  containers:
  - name: app
    image: ngovanhuy0241/k8s_container:node
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085
