# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04-arm64"
  config.vm.network "private_network", ip: "172.16.11.103"
  config.vm.hostname = "rancher"

  config.vm.provider "libvirt" do |vb|
     vb.name = "rancher"
     vb.cpus = 3
     vb.memory = "3096"
     vb.gui = true
  end

  config.vm.provision "shell", path: "./../setup-docker.sh"

  config.vm.provision "shell", inline: <<-SHELL

    echo "root password"
    # # Centos
    # echo "123" | passwd --stdin root
    # # Ubuntu
    echo 'root:123' | sudo chpasswd

    # # Centos
    # sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    cat >>/etc/ssh/sshd_config<<EOF
PermitRootLogin yes
PasswordAuthentication yes
EOF
    systemctl reload sshd

cat >>/etc/hosts<<EOF
172.16.11.100 master.xtl
172.16.11.101 worker1.xtl
172.16.11.102 worker2.xtl
EOF

  SHELL
end
