apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: nginx-ingress
spec:
  storageClassName: mystorageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi